// Models/Assignment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace University_OnlineCourse_Management_System.Models
{
    public class Assignment
    {
        // Primary Key, automatically generated by the database
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int AssignmentID { get; set; }

        // Foreign Key to the Courses table
        [Required]
        [MaxLength(20)]
        public string CourseID { get; set; }

        // Navigation property to the Course entity
        [ForeignKey("CourseID")]
        public Course Course { get; set; }

        // Foreign Key to the Instructors table
        [Required]
        [MaxLength(20)]
        public string InstructorID { get; set; }

        // Navigation property to the Instructor entity (assuming you have an Instructor model)
        // [ForeignKey("InstructorID")]
        // public Instructor Instructor { get; set; }

        // Title of the assignment
        [Required]
        [MaxLength(255)]
        public string Title { get; set; }

        // Detailed description of the assignment (can be longer text)
        public string Description { get; set; }

        // Date and time when the assignment is due
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime DueDate { get; set; }

        // Maximum possible score for the assignment
        [Required]
        public int MaxScore { get; set; }
    }
}
